
@hostname = localhost 
@port = 3000
@uri = interests
@host = {{hostname}}:{{port}}
@contentType = application/json 


POST http://{{host}}/{{uri}} HTTP/1.1
Content-Type: {{contentType}}

{ 
  "name": "first interest",
  "active": true
}

###

GET http://{{host}}/{{uri}} HTTP/1.1
Content-Type: {{contentType}}

###

GET http://{{host}}/{{uri}}/6a61b062-ba16-44c1-b7a7-44bbfb2a8785 HTTP/1.1
Content-Type: {{contentType}}

###

PUT http://{{host}}/{{uri}}/6a61b062-ba16-44c1-b7a7-44bbfb2a8785 HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "other interest",
  "active": false
}

###

DELETE http://{{host}}/{{uri}}/-6a61b062-ba16-44c1-b7a7-44bbfb2a8785 HTTP/1.1
Content-Type: {{contentType}}

